/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package chess;

import chess.model.*;
/**
 *
 * @author Fahad
 */
public class GameSetupWindow extends javax.swing.JDialog {

    GameWindow gameWindow;
    java.awt.Frame parent;

    /** Creates new form GameSetupWindow */
    public GameSetupWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        this.setResizable(false);
        this.getRootPane().setDefaultButton(playButton);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        playerOneButtonGroup = new javax.swing.ButtonGroup();
        playerTwoButtonGroup = new javax.swing.ButtonGroup();
        blackTimeButtonGroup = new javax.swing.ButtonGroup();
        whiteTimeButtonGroup = new javax.swing.ButtonGroup();
        bonusTimeButtonGroup = new javax.swing.ButtonGroup();
        whiteMinSecGroup = new javax.swing.ButtonGroup();
        blackMinSecGroup = new javax.swing.ButtonGroup();
        playButton = new javax.swing.JButton();
        playerOnePanel = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        playerOneComputerCheckbox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        playerOneHumanCheckbox = new javax.swing.JCheckBox();
        playerOneDifficultySlider = new javax.swing.JSlider();
        playerTwoPanel = new javax.swing.JPanel();
        jSlider3 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        playerTwoComputerCheckbox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        playerTwoHumanCheckbox = new javax.swing.JCheckBox();
        playerTwoDifficultySlider = new javax.swing.JSlider();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bonusTimeOne = new javax.swing.JCheckBox();
        bonusTimeThirty = new javax.swing.JCheckBox();
        bonusTimeTen = new javax.swing.JCheckBox();
        bonusTimeSixty = new javax.swing.JCheckBox();
        isBonusCheckBox = new javax.swing.JCheckBox();
        whiteTimeField = new javax.swing.JTextField();
        blackTimeField = new javax.swing.JTextField();
        minCheck = new javax.swing.JCheckBox();
        secCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(chess.ChessApp.class).getContext().getResourceMap(GameSetupWindow.class);
        playButton.setText(resourceMap.getString("playButton.text")); // NOI18N
        playButton.setName("playButton"); // NOI18N
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        playerOnePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("playerOnePanel.border.title"))); // NOI18N
        playerOnePanel.setName("playerOnePanel"); // NOI18N

        jSlider1.setName("jSlider1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setEnabled(false);
        jLabel2.setName("jLabel2"); // NOI18N

        playerOneButtonGroup.add(playerOneComputerCheckbox);
        playerOneComputerCheckbox.setText(resourceMap.getString("playerOneComputerCheckbox.text")); // NOI18N
        playerOneComputerCheckbox.setName("playerOneComputerCheckbox"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        playerOneButtonGroup.add(playerOneHumanCheckbox);
        playerOneHumanCheckbox.setSelected(true);
        playerOneHumanCheckbox.setText(resourceMap.getString("playerOneHumanCheckbox.text")); // NOI18N
        playerOneHumanCheckbox.setName("playerOneHumanCheckbox"); // NOI18N

        playerOneDifficultySlider.setEnabled(false);
        playerOneDifficultySlider.setName("playerOneDifficultySlider"); // NOI18N

        javax.swing.GroupLayout playerOnePanelLayout = new javax.swing.GroupLayout(playerOnePanel);
        playerOnePanel.setLayout(playerOnePanelLayout);
        playerOnePanelLayout.setHorizontalGroup(
            playerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerOnePanelLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
            .addGroup(playerOnePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(playerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerOnePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playerOneHumanCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerOneComputerCheckbox))
                    .addGroup(playerOnePanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(playerOneDifficultySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        playerOnePanelLayout.setVerticalGroup(
            playerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerOnePanelLayout.createSequentialGroup()
                .addGroup(playerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(playerOneHumanCheckbox)
                    .addComponent(playerOneComputerCheckbox))
                .addGap(18, 18, 18)
                .addGroup(playerOnePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerOnePanelLayout.createSequentialGroup()
                        .addComponent(playerOneDifficultySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)))
        );

        playerTwoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("playerTwoPanel.border.title"))); // NOI18N
        playerTwoPanel.setName("playerTwoPanel"); // NOI18N

        jSlider3.setName("jSlider3"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setEnabled(false);
        jLabel3.setName("jLabel3"); // NOI18N

        playerTwoButtonGroup.add(playerTwoComputerCheckbox);
        playerTwoComputerCheckbox.setText(resourceMap.getString("playerTwoComputerCheckbox.text")); // NOI18N
        playerTwoComputerCheckbox.setName("playerTwoComputerCheckbox"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        playerTwoButtonGroup.add(playerTwoHumanCheckbox);
        playerTwoHumanCheckbox.setSelected(true);
        playerTwoHumanCheckbox.setText(resourceMap.getString("playerTwoHumanCheckbox.text")); // NOI18N
        playerTwoHumanCheckbox.setName("playerTwoHumanCheckbox"); // NOI18N

        playerTwoDifficultySlider.setEnabled(false);
        playerTwoDifficultySlider.setName("playerTwoDifficultySlider"); // NOI18N

        javax.swing.GroupLayout playerTwoPanelLayout = new javax.swing.GroupLayout(playerTwoPanel);
        playerTwoPanel.setLayout(playerTwoPanelLayout);
        playerTwoPanelLayout.setHorizontalGroup(
            playerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerTwoPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(playerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerTwoPanelLayout.createSequentialGroup()
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerTwoPanelLayout.createSequentialGroup()
                        .addGroup(playerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(playerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(playerTwoPanelLayout.createSequentialGroup()
                                .addComponent(playerTwoHumanCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerTwoComputerCheckbox))
                            .addComponent(playerTwoDifficultySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        playerTwoPanelLayout.setVerticalGroup(
            playerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerTwoPanelLayout.createSequentialGroup()
                .addGroup(playerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(playerTwoHumanCheckbox)
                    .addComponent(playerTwoComputerCheckbox))
                .addGap(18, 18, 18)
                .addGroup(playerTwoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerTwoPanelLayout.createSequentialGroup()
                        .addComponent(playerTwoDifficultySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        bonusTimeButtonGroup.add(bonusTimeOne);
        bonusTimeOne.setSelected(true);
        bonusTimeOne.setText(resourceMap.getString("bonusTimeOne.text")); // NOI18N
        bonusTimeOne.setName("bonusTimeOne"); // NOI18N

        bonusTimeButtonGroup.add(bonusTimeThirty);
        bonusTimeThirty.setText(resourceMap.getString("bonusTimeThirty.text")); // NOI18N
        bonusTimeThirty.setName("bonusTimeThirty"); // NOI18N

        bonusTimeButtonGroup.add(bonusTimeTen);
        bonusTimeTen.setText(resourceMap.getString("bonusTimeTen.text")); // NOI18N
        bonusTimeTen.setName("bonusTimeTen"); // NOI18N

        bonusTimeButtonGroup.add(bonusTimeSixty);
        bonusTimeSixty.setText(resourceMap.getString("bonusTimeSixty.text")); // NOI18N
        bonusTimeSixty.setName("bonusTimeSixty"); // NOI18N

        isBonusCheckBox.setSelected(true);
        isBonusCheckBox.setText(resourceMap.getString("isBonusCheckBox.text")); // NOI18N
        isBonusCheckBox.setName("isBonusCheckBox"); // NOI18N
        isBonusCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isBonusCheckBoxActionPerformed(evt);
            }
        });

        whiteTimeField.setText(resourceMap.getString("whiteTimeField.text")); // NOI18N
        whiteTimeField.setName("whiteTimeField"); // NOI18N

        blackTimeField.setText(resourceMap.getString("blackTimeField.text")); // NOI18N
        blackTimeField.setName("blackTimeField"); // NOI18N

        whiteMinSecGroup.add(minCheck);
        minCheck.setSelected(true);
        minCheck.setText(resourceMap.getString("minCheck.text")); // NOI18N
        minCheck.setName("minCheck"); // NOI18N

        whiteMinSecGroup.add(secCheck);
        secCheck.setText(resourceMap.getString("secCheck.text")); // NOI18N
        secCheck.setName("secCheck"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isBonusCheckBox)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(blackTimeField)
                            .addComponent(whiteTimeField, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secCheck))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bonusTimeOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bonusTimeTen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bonusTimeThirty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bonusTimeSixty)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(whiteTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(blackTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isBonusCheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minCheck)
                            .addComponent(secCheck))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bonusTimeTen)
                        .addComponent(bonusTimeOne))
                    .addComponent(bonusTimeThirty)
                    .addComponent(bonusTimeSixty))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerOnePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerTwoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerOnePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerTwoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Player playerOne;
        Player playerTwo;
        gameWindow = new GameWindow();
        gameWindow.setLocationRelativeTo(this);
        gameWindow.setVisible(true);

        if (playerOneComputerCheckbox.isSelected()) {
            playerOne = new ComputerPlayer();
        } else {
            playerOne = new HumanPlayer(gameWindow);
        }
        if (playerTwoComputerCheckbox.isSelected()) {
            playerTwo = new ComputerPlayer();
        } else {
            playerTwo = new HumanPlayer(gameWindow);
        }
        int whiteTime = Integer.parseInt(whiteTimeField.getText());
        int blackTime = Integer.parseInt(blackTimeField.getText());
        int bonus = 0;
        if (whiteTime < 0) {
            System.out.println("Input Error");
        }
        if (blackTime < 0) {
            System.out.println("Input Error");
        }
        if (isBonusCheckBox.isSelected()) {
            if (bonusTimeOne.isSelected()) {
                bonus = 1;
            }
            if (bonusTimeTen.isSelected()) {
                bonus = 10;
            }
            if (bonusTimeThirty.isSelected()) {
                bonus = 30;
            }
            if (bonusTimeSixty.isSelected()) {
                bonus = 60;
            }
        } else {
            bonus = 0;
        }
        TimeConditions tc;
        if (secCheck.isSelected()) {
            tc = new TimeConditions(whiteTime, blackTime, bonus, false);
        } else {
            tc = new TimeConditions(whiteTime, blackTime, bonus, true);
        }
        gameWindow.startGame(playerOne, playerTwo, tc);
        dispose();
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        parent.setVisible(true);
    }
        // TODO add your handling code here:}

    private void isBonusCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {
        boolean isBonus = isBonusCheckBox.isSelected();
        if (isBonus) {
            bonusTimeOne.setEnabled(true);
            bonusTimeTen.setEnabled(true);
            bonusTimeThirty.setEnabled(true);
            bonusTimeSixty.setEnabled(true);
        } else {
            bonusTimeOne.setEnabled(false);
            bonusTimeTen.setEnabled(false);
            bonusTimeThirty.setEnabled(false);
            bonusTimeSixty.setEnabled(false);
        }
    }
    // Variables declaration - do not modify
    private javax.swing.ButtonGroup blackMinSecGroup;
    private javax.swing.ButtonGroup blackTimeButtonGroup;
    private javax.swing.JTextField blackTimeField;
    private javax.swing.ButtonGroup bonusTimeButtonGroup;
    private javax.swing.JCheckBox bonusTimeOne;
    private javax.swing.JCheckBox bonusTimeSixty;
    private javax.swing.JCheckBox bonusTimeTen;
    private javax.swing.JCheckBox bonusTimeThirty;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox isBonusCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JCheckBox minCheck;
    private javax.swing.JButton playButton;
    private javax.swing.ButtonGroup playerOneButtonGroup;
    private javax.swing.JCheckBox playerOneComputerCheckbox;
    private javax.swing.JSlider playerOneDifficultySlider;
    private javax.swing.JCheckBox playerOneHumanCheckbox;
    private javax.swing.JPanel playerOnePanel;
    private javax.swing.ButtonGroup playerTwoButtonGroup;
    private javax.swing.JCheckBox playerTwoComputerCheckbox;
    private javax.swing.JSlider playerTwoDifficultySlider;
    private javax.swing.JCheckBox playerTwoHumanCheckbox;
    private javax.swing.JPanel playerTwoPanel;
    private javax.swing.JCheckBox secCheck;
    private javax.swing.ButtonGroup whiteMinSecGroup;
    private javax.swing.ButtonGroup whiteTimeButtonGroup;
    private javax.swing.JTextField whiteTimeField;
    // End of variables declaration
}
